'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://guymon-ok.karservices.com/Webservice/Eservice.asmx")>  _
        Public ReadOnly Property KAR_Lot_SmartClient_karservices_cactus_smartclient_kar_smartclient_webservice() As String
            Get
                Return CType(Me("KAR_Lot_SmartClient_karservices_cactus_smartclient_kar_smartclient_webservice"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/webservice/eservice.asmx")>  _
        Public Property EnhancedWebServicePath() As String
            Get
                Return CType(Me("EnhancedWebServicePath"),String)
            End Get
            Set
                Me("EnhancedWebServicePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/webservice/service.asmx")>  _
        Public Property BasicWebServicePath() As String
            Get
                Return CType(Me("BasicWebServicePath"),String)
            End Get
            Set
                Me("BasicWebServicePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\karlot\export")>  _
        Public Property DataExportPath() As String
            Get
                Return CType(Me("DataExportPath"),String)
            End Get
            Set
                Me("DataExportPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\karlot\cache")>  _
        Public Property DataCacheDirectory() As String
            Get
                Return CType(Me("DataCacheDirectory"),String)
            End Get
            Set
                Me("DataCacheDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Network")>  _
        Public Property ConnectionType() As String
            Get
                Return CType(Me("ConnectionType"),String)
            End Get
            Set
                Me("ConnectionType") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://guymon-ok.karservices.com/Webservice/service.asmx")>  _
        Public ReadOnly Property KAR_Lot_SmartClient_karservices_cactus_webservices_Service() As String
            Get
                Return CType(Me("KAR_Lot_SmartClient_karservices_cactus_webservices_Service"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("carriers.xml")>  _
        Public Property CarriersCacheFile() As String
            Get
                Return CType(Me("CarriersCacheFile"),String)
            End Get
            Set
                Me("CarriersCacheFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("inbound.xml")>  _
        Public Property InboundSheetCacheFile() As String
            Get
                Return CType(Me("InboundSheetCacheFile"),String)
            End Get
            Set
                Me("InboundSheetCacheFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ActiveTrailers.xml")>  _
        Public Property ActiveTrailersCacheFile() As String
            Get
                Return CType(Me("ActiveTrailersCacheFile"),String)
            End Get
            Set
                Me("ActiveTrailersCacheFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TMP")>  _
        Public Property StationID() As String
            Get
                Return CType(Me("StationID"),String)
            End Get
            Set
                Me("StationID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("WashOnly")>  _
        Public Property WashMode() As String
            Get
                Return CType(Me("WashMode"),String)
            End Get
            Set
                Me("WashMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/help/karlot%20faq.html")>  _
        Public Property HelpURL() As String
            Get
                Return CType(Me("HelpURL"),String)
            End Get
            Set
                Me("HelpURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/layout.kar.txt")>  _
        Public Property LayoutURL() As String
            Get
                Return CType(Me("LayoutURL"),String)
            End Get
            Set
                Me("LayoutURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/dispatch_bg.png")>  _
        Public Property BackgroundURL() As String
            Get
                Return CType(Me("BackgroundURL"),String)
            End Get
            Set
                Me("BackgroundURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnhancedTasking() As Boolean
            Get
                Return CType(Me("EnhancedTasking"),Boolean)
            End Get
            Set
                Me("EnhancedTasking") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("guymon-ok.karservices.com")>  _
        Public Property LocalKarLotServer() As String
            Get
                Return CType(Me("LocalKarLotServer"),String)
            End Get
            Set
                Me("LocalKarLotServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("guymon-ok.karservices.com")>  _
        Public Property RemoteWebServer() As String
            Get
                Return CType(Me("RemoteWebServer"),String)
            End Get
            Set
                Me("RemoteWebServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property LocalServerPort() As String
            Get
                Return CType(Me("LocalServerPort"),String)
            End Get
            Set
                Me("LocalServerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property RemoteServerPort() As String
            Get
                Return CType(Me("RemoteServerPort"),String)
            End Get
            Set
                Me("RemoteServerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property HttpsRemote() As Boolean
            Get
                Return CType(Me("HttpsRemote"),Boolean)
            End Get
            Set
                Me("HttpsRemote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AllowTrailerCheckInOut() As Boolean
            Get
                Return CType(Me("AllowTrailerCheckInOut"),Boolean)
            End Get
            Set
                Me("AllowTrailerCheckInOut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AllowBarcodeActivation() As Boolean
            Get
                Return CType(Me("AllowBarcodeActivation"),Boolean)
            End Get
            Set
                Me("AllowBarcodeActivation") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SomeApiKey")>  _
        Public ReadOnly Property ApiKey() As String
            Get
                Return CType(Me("ApiKey"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://guymon-ok.karservices.com/api/")>  _
        Public Property ApiBaseURL() As String
            Get
                Return CType(Me("ApiBaseURL"),String)
            End Get
            Set
                Me("ApiBaseURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property ViewLegacyPalletInfoOnDockCallout() As Boolean
            Get
                Return CType(Me("ViewLegacyPalletInfoOnDockCallout"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property ViewLegacyPalletInfoOnDockCallin() As Boolean
            Get
                Return CType(Me("ViewLegacyPalletInfoOnDockCallin"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property CanEditPalletOnDockCallout() As Boolean
            Get
                Return CType(Me("CanEditPalletOnDockCallout"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property ViewPalletLoadDataOnDockCallin() As Boolean
            Get
                Return CType(Me("ViewPalletLoadDataOnDockCallin"),Boolean)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.KAR_Lot_SmartClient.My.MySettings
            Get
                Return Global.KAR_Lot_SmartClient.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
